// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangSachMini.Data;

#nullable disable

namespace QuanLyCuaHangSachMini.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404002817_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChuHoaDon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.HoaDon_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("SachID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("SachID");

                    b.ToTable("HoaDon_ChiTiet", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachHang")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("MaNhaCungCap")
                        .IsUnique();

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhaXuatBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaNhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("MaNhaXuatBan")
                        .IsUnique();

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("QuyenHan")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhatKyHeThong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BangDuLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("KhoaChinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.PhieuNhap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChuPhieuNhap")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhaCungCapID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaPhieuNhap")
                        .IsUnique();

                    b.HasIndex("NhaCungCapID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhieuNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.PhieuNhap_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhieuNhapID")
                        .HasColumnType("int");

                    b.Property<int>("SachID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhieuNhapID");

                    b.HasIndex("SachID");

                    b.ToTable("PhieuNhap_ChiTiet", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.Sach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("NhaXuatBanID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TheLoaiID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("MaSach")
                        .IsUnique();

                    b.HasIndex("NhaXuatBanID");

                    b.HasIndex("TheLoaiID");

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.TheLoai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("MaTheLoai")
                        .IsUnique();

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.HoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.HoaDon_ChiTiet", b =>
                {
                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.HoaDon", "HoaDon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.Sach", "Sach")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("SachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhatKyHeThong", b =>
                {
                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.NhanVien", "NhanVien")
                        .WithMany("NhatKyHeThong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhap")
                        .HasForeignKey("NhaCungCapID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.NhanVien", "NhanVien")
                        .WithMany("PhieuNhap")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.PhieuNhap_ChiTiet", b =>
                {
                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.PhieuNhap", "PhieuNhap")
                        .WithMany("PhieuNhap_ChiTiet")
                        .HasForeignKey("PhieuNhapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.Sach", "Sach")
                        .WithMany("PhieuNhap_ChiTiet")
                        .HasForeignKey("SachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.Sach", b =>
                {
                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Sach")
                        .HasForeignKey("NhaXuatBanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangSachMini.Data.Entity.TheLoai", "TheLoai")
                        .WithMany("Sach")
                        .HasForeignKey("TheLoaiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaXuatBan");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.HoaDon", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.KhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhaXuatBan", b =>
                {
                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.NhanVien", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("NhatKyHeThong");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.PhieuNhap", b =>
                {
                    b.Navigation("PhieuNhap_ChiTiet");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.Sach", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");

                    b.Navigation("PhieuNhap_ChiTiet");
                });

            modelBuilder.Entity("QuanLyCuaHangSachMini.Data.Entity.TheLoai", b =>
                {
                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
